name: minimalblue-lxqt-main-userns-hardened

description: ublue images for lxqt

base-image: ghcr.io/minimalblue/lxqt-main-userns-hardened

image-version: 41 

modules:
  - from-file: common/common-modules.yml
  - from-file: common/flatpaks-modules.yml
  - from-file: common/mullvad-modules.yml
  - from-file: common/fonts.yml