# image will be published to ghcr.io/<user>/<name>
name: ulxqt
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - alacritty
      - breeze-cursor-theme
      - breeze-gtk
      - breeze-icon-theme
      - fedora-release-identity-lxqt
      - fedora-release-lxqt
      - firewall-config
      - fish
      - initial-setup-gui
      - kvantum
      - libdbusmenu-lxqt
      - liblxqt
      - libqtxdg
      - lximage-qt
      - lxqt-about
      - lxqt-admin
      - lxqt-archiver
      - lxqt-build-tools
      - lxqt-common
      - lxqt-config
      - lxqt-config-randr
      - lxqt-globalkeys
      - lxqt-l10n
      - lxqt-menu-data
      - lxqt-notificationd
      - lxqt-openssh-askpass
      - lxqt-panel
      - lxqt-policykit
      - lxqt-powermanagement
      - lxqt-qtplugin
      - lxqt-runner
      - lxqt-session
      - lxqt-sudo
      - lxqt-themes
      - lxqt-themes-fedora
      - lxqt-wallet
      - mesa-dri-drivers
      - mesa-vulkan-drivers
      - micro
      - network-manager-applet
      - nm-connection-editor
      - notification-daemon
      - obconf
      - openbox
      - pavucontrol-qt
      - pcmanfm-qt
      - perl-File-MimeInfo
      - plymouth-system-theme
      - podman-compose
      - qt5-qtimageformats
      - samba-client
      - sddm
      - sddm-themes
      - starship
      - upower
      - xdg-desktop-portal-kde
      - xdg-desktop-portal-lxqt
      - xdg-user-dirs
      - xfwm4
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
       - firefox
       - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

